name: Tests on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests-on-pr:
    uses: scikit-package/release-scripts/.github/workflows/_tests-on-pr.yml@v0
    with:
      project: diffpy.cmi
      c_extension: false
      headless: false
      python_version: 3.13
      run: |
        set -Eeuo pipefail
        echo "Test cmds"
        cmi -h
        cmi env
        cmi pack list
        cmi profile list
        cmi install plotting
        if [ "${RUNNER_OS}" != "Windows" ]; then
          conda list | grep -i ipympl
        else
          source "$(cygpath -u "$CONDA")/etc/profile.d/conda.sh"
          conda activate test
          conda list | grep -i ipympl
        fi

        echo "Running tests for diffpy.cmi dependencies"
        cmi install _tests
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
